- packages/ui/package.json
- packages/ui/src/index.tsx
- packages/ui/src/tooltip/index.ts
- packages/ui/src/tooltip/tooltip.stories.tsx
- packages/ui/src/tooltip/tooltip.tsx
- pnpm-lock.yaml
> feat: create tooltip component

- apps/mochi-web/app/layout/navbar.tsx
- apps/mochi-web/components/auth-layout.tsx
- packages/ui/src/sidebar/sidebar-item-list.tsx
- packages/ui/src/sidebar/sidebar-item.tsx
- packages/ui/src/sidebar/sidebar.tsx
> fix: sidebar

- apps/mochi-web/components/auth-layout.tsx
- packages/ui/src/sidebar/sidebar-item-list.tsx
- packages/ui/src/sidebar/sidebar-item.tsx
- packages/ui/src/sidebar/sidebar.tsx
> fix: sidebar state

- packages/ui/src/sidebar/sidebar-item-list.tsx
- packages/ui/src/sidebar/sidebar.tsx
> fix: sidebar tooltip and responsive

- .gitignore
- apps/mochi-web/components/Home/SetupIsSimple.tsx
- apps/mochi-web/components/MochiWidget/PlatformPicker/PlatformPicker.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenPicker.tsx
- apps/mochi-web/components/MochiWidget/index.tsx
- apps/mochi-web/components/MochiWidget/tip.tsx
- apps/mochi-web/components/receipt/index.tsx
- apps/mochi-web/components/receipt/template.tsx
- apps/mochi-web/envs.ts
- apps/mochi-web/next.config.js
- apps/mochi-web/pages/_app.tsx
- apps/mochi-web/pages/_components.tsx
- apps/mochi-web/pages/index.tsx
- apps/mochi-web/pages/tx/[id].tsx
- packages/ui/.storybook/manager.js
- packages/ui/package.json
- pnpm-lock.yaml
env variable replace `INVITE_LINK` with `ADD_DISCORD_BOT_LINK`
> fix: cleanup envs and build step

- packages/ui/src/sidebar/sidebar-item.tsx
> fix: sidebar footer behavior and safari ui break

- packages/tailwind-config/tailwind.config.ts
- packages/ui/src/button/button.stories.tsx
- packages/ui/src/button/button.tsx
- packages/ui/src/button/index.ts
- packages/ui/src/icon-button/icon-button.stories.tsx
- packages/ui/src/icon-button/icon-button.tsx
- packages/ui/src/icon-button/index.ts
> feat: button component

- packages/ui/src/sidebar/sidebar-item.tsx
- packages/ui/src/sidebar/sidebar.stories.tsx
[Ticket](https://www.notion.so/console-labs/Menu-Item-khi-selected-th-gi-shadow-e814a0b765c5423d824c3480f7ceb0fe)
[screen-capture (16).webm](https://github.com/consolelabs/websites/assets/88917321/a0870c48-b619-4cc5-8224-d646305438ba)
> feat: add background to selected section sidebar

- apps/mochi-web/components/auth-layout.tsx
- apps/mochi-web/components/header.tsx
https://www.notion.so/console-labs/Topbar-Container-background-color-982cc649f3ea44c58436479bb114010b
> fix: set background white for topbar and container

- apps/mochi-web/package.json
- pnpm-lock.yaml
> fix: recent transactions schema mismatch

- .commitlintrc.js
- .husky/commit-msg
- .husky/post-merge
- .husky/pre-commit
- package.json
- packages/eslint-config-custom/react.js
- Post-merge for auto install node_modules after pull merged
- Commit-msg for linting the commit message
- Add lint-staged for format only files changed
> chore: add more post scripts and commitlint

- packages/tailwind-config/tailwind.config.ts
- packages/ui/src/button/button.stories.tsx
- packages/ui/src/button/button.tsx
> fix: button variants and colors

- apps/mochi-web/components/AuthWidget/AuthPanel.tsx
- apps/mochi-web/components/AuthWidget/ConnectButton.tsx
- apps/mochi-web/components/AuthWidget/PanelContainer.tsx
- apps/mochi-web/components/AuthWidget/PanelHeader.tsx
- apps/mochi-web/components/AuthWidget/types.ts
- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/components/MochiWidget/MessagePicker/MessagePicker.tsx
- apps/mochi-web/components/MochiWidget/Recipient/Recipient.tsx
- apps/mochi-web/components/MochiWidget/SourcePicker/SourcePicker.tsx
- apps/mochi-web/components/MochiWidget/ThemePicker/ThemePicker.tsx
- apps/mochi-web/components/MochiWidget/Tip/StepOne.tsx
- apps/mochi-web/components/MochiWidget/Tip/StepTwo.tsx
- apps/mochi-web/components/MochiWidget/Tip/index.tsx
- apps/mochi-web/components/MochiWidget/Tip/store.ts
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenPicker.tsx
- apps/mochi-web/components/MochiWidget/index.tsx
> chore: update tip latest UI

- .commitlintrc.js
- .husky/commit-msg
- .husky/post-merge
- .husky/pre-commit
- .prettierrc
- package.json
- packages/eslint-config-custom/react.js
> chore: commitlint config

- apps/mochi-web/components/auth-layout.tsx
- apps/mochi-web/components/header.tsx
- Migrate to use new AuthPanel
- 
[screen-capture (19).webm](https://github.com/consolelabs/websites/assets/88917321/ab6df9ef-1111-4c1d-9a2e-3bef269626e3)
> feat: migrate new auth panel ui

- .vscode/settings.json
- packages/ui/.storybook/manager.js
- packages/ui/src/icons/components/icon-arrow-left.tsx
- packages/ui/src/icons/components/icon-arrow-right.tsx
- packages/ui/src/icons/svg/arrow-left.svg
- packages/ui/src/icons/svg/arrow-right.svg
- packages/ui/src/pagination/index.tsx
- packages/ui/src/pagination/pagination.stories.tsx
- packages/ui/src/pagination/pagination.tsx
> feat(ui): add pagination component

- .vscode/settings.json
- packages/ui/.storybook/manager.js
- packages/ui/package.json
- packages/ui/src/icons/components/icon-arrow-left.tsx
- packages/ui/src/icons/components/icon-arrow-right.tsx
- packages/ui/src/icons/svg/arrow-left.svg
- packages/ui/src/icons/svg/arrow-right.svg
- packages/ui/src/pagination/index.tsx
- packages/ui/src/pagination/pagination.stories.tsx
- packages/ui/src/pagination/pagination.tsx
- packages/ui/src/table/index.tsx
- packages/ui/src/table/table.stories.tsx
- packages/ui/src/table/table.tsx
- pnpm-lock.yaml
> feat(ui): add table component

- packages/ui/src/button/button.tsx
> fix: button size

- .changeset/config.json
- .github/actions/setup-env/actions.yml
- .github/workflows/release.yml
- .npmrc
- .npmrc.example
- package.json
- packages/ui/package.json
- pnpm-lock.yaml
> feat: add changesets

- .github/workflows/release.yml
> fix: checkout branch

- apps/mochi-web/package.json
- apps/mochi-web/store/profile.ts
- pnpm-lock.yaml
> fix: render profile name

- packages/components/accordion/package.json
- packages/components/alert/package.json
- packages/components/avatar/package.json
- packages/components/badge/package.json
- packages/components/dropdown/package.json
- packages/components/heading/package.json
- packages/components/input/package.json
- packages/components/list/package.json
- packages/components/login-widget/package.json
- packages/components/mochi-store/package.json
- packages/components/popover/package.json
- packages/components/profile-badge/package.json
- packages/components/section-list/package.json
- packages/components/sidebar/package.json
- packages/components/switch/package.json
- packages/components/tooltip/package.json
- packages/core/package.json
- packages/icons/clean-package.config.json
- packages/icons/package.json
- pnpm-lock.yaml
> chore: update scripts

- apps/mochi-web/components/Header/MobileNav.tsx
- apps/mochi-web/hooks/useLockScreenScroll.ts
> fix: lock underly screen when open mobile nav

- apps/mochi-web/components/Header/Header.tsx
disable scroll on mobile nav while not open
> fix: wrong disable scroll on mobile screen

- .github/workflows/release.yml
> chore: add permissions pr

- .changeset/rare-dolphins-pay.md
- .gitignore
- package.json
> fix: missing build packages

- .changeset/smart-forks-push.md
> fix: missing build packages on CI

- .changeset/slimy-cameras-look.md
- apps/mochi-web/tailwind.config.js
- packages/core/README.md
- packages/storybook/tailwind.config.js
- packages/tailwind-config/plugin.ts
- packages/theme/src/plugin.ts
- packages/ui/tailwind.config.ts
> fix(theme): rename mochi to consolelabs

- .changeset/soft-seas-hope.md
- packages/components/alert/src/index.ts
- packages/components/badge/src/index.ts
- packages/components/dropdown/src/index.ts
- packages/components/list/src/index.ts
- packages/theme/src/components/accordion.ts
- packages/theme/src/components/alert.ts
- packages/theme/src/components/avatar.ts
- packages/theme/src/components/badge.ts
- packages/theme/src/components/button.ts
- packages/theme/src/components/dropdown.ts
- packages/theme/src/components/input-field.ts
- packages/theme/src/components/input.ts
- packages/theme/src/components/list.ts
- packages/theme/src/components/select.ts
- packages/theme/src/components/separator.ts
- packages/theme/src/components/tabs.ts
- packages/theme/src/components/toggle-button.ts
> fix(theme): update module export

- packages/core/README.md
> docs: add ui philosophy section

- packages/components/polymorphic/.eslintrc.js
- packages/components/polymorphic/package.json
- packages/components/polymorphic/src/index.ts
- packages/components/polymorphic/src/polymorphic.tsx
- packages/components/polymorphic/tsconfig.json
- packages/components/polymorphic/tsup.config.ts
- pnpm-lock.yaml
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=bc18395a3e10483b8ab3dc0e828fa79f&pm=s
> feat: polymorphic component

- packages/core/README.md
> docs(core): fix wrong tailwind content path

- .changeset/config.json
- package.json
- pnpm-lock.yaml
> chore(release): ignore release ui components

- apps/mochi-web/.npmrc
- apps/mochi-web/package.json
- apps/mochi-web/tailwind.config.js
- pnpm-lock.yaml
> chore: update mochi web config

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/questions.md
- .github/dependabot.yml
> docs: add issue templates

- .github/workflows/release.yml
- scripts/check-skip-apps-commit
- vercel.json
> ci(vercel): add ignore command to detect build Apps

- apps/mochi-web/components/Feed/index.tsx
- apps/mochi-web/components/Feed/store.ts
- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/components/landing/LivePlatforms.tsx
- apps/mochi-web/components/landing/SoonAvailablePlatforms.tsx
- apps/mochi-web/pages/index.tsx
- apps/mochi-web/styles/global.css
> fix: new homepage

- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/components/Receipt/utils.ts
- apps/mochi-web/pages/tx/[id].tsx
> fix: use UI.render instead of resolve

- apps/mochi-web/constants/api.ts
- apps/mochi-web/pages/tx/[id].tsx
> fix: add timeout in tx page

- .github/workflows/release.yml
- scripts/check-skip-apps-commit
> fix: regex test skip ci

- .github/workflows/release.yml
- scripts/check-build-apps.js
> fix: regex test skip apps

- .changeset/gold-buckets-breathe.md
- packages/components/accordion/README.md
- packages/components/alert/README.md
- packages/components/avatar/README.md
- packages/components/badge/README.md
- packages/components/button/README.md
- packages/components/checkbox/README.md
- packages/components/dropdown/README.md
- packages/components/heading/README.md
- packages/components/icon-button/README.md
- packages/components/input-field/README.md
- packages/components/input/README.md
- packages/components/list/README.md
- packages/components/login-widget/README.md
- packages/components/mochi-store/README.md
- packages/components/modal/README.md
- packages/components/pagination/README.md
- packages/components/polymorphic/README.md
- packages/components/popover/README.md
- packages/components/profile-badge/README.md
- packages/components/section-list/README.md
- packages/components/select/README.md
- packages/components/separator/README.md
- packages/components/sidebar/README.md
- packages/components/table/README.md
- packages/components/tabs/README.md
- packages/components/tooltip/README.md
- packages/components/typography/README.md
> feat: write readme for all component packages

- .github/workflows/release.yml
- packages/components/accordion/__tests__/accordion.test.tsx
- packages/components/dropdown/__tests__/dropdown.test.tsx
- packages/components/heading/__tests__/heading.test.tsx
- packages/components/icon-button/__tests__/__snapshots__/icon-button.test.tsx.snap
- packages/components/icon-button/__tests__/icon-button.test.tsx
- packages/components/icon-button/tsconfig.json
- packages/components/input-field/__tests__/input-field.test.tsx
- packages/components/input/__tests__/input.test.tsx
- packages/components/tooltip/__tests__/tooltip.test.tsx
- packages/components/tooltip/tsconfig.json
- packages/components/typography/__tests__/typography.test.tsx
- packages/components/typography/tsconfig.json
> test: dropdown and input fields

- apps/mochi-web/components/auth-layout.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=fdbe034e92a14c38bd6de2195e9616db&pm=s
> fix: sidebar not full height

- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/components/MochiWidget/ErrorMessage/ErrorMessage.tsx
- apps/mochi-web/components/MochiWidget/Recipient/Recipient.tsx
- apps/mochi-web/components/MochiWidget/Tip/StepOne.tsx
- apps/mochi-web/components/MochiWidget/Tip/store.ts
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenItem.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenList.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenPicker.tsx
- apps/mochi-web/components/MochiWidget/WalletPicker/WalletItem.tsx
- apps/mochi-web/components/MochiWidget/WalletPicker/WalletPicker.tsx
- apps/mochi-web/store/wallets.ts
- apps/mochi-web/utils/number.ts
> feat: handle asset and amount

- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/utils/number.ts
> chore: format token input

- .changeset/thirty-deers-deliver.md
- apps/mochi-web/pages/tx/[id].tsx
- packages/components/login-widget/src/providers.ts
- pnpm-lock.yaml
> fix: login-widget solana connect function window type check

- apps/mochi-web/components/Header/MobileNavAccordionItem.tsx
> refactor: migrate to consolelab-core accordion

- .changeset/strange-bugs-doubt.md
- .changeset/wet-pets-fold.md
- packages/components/button/src/button.tsx
- packages/components/popover/package.json
- packages/components/popover/stories/popover.stories.tsx
- pnpm-lock.yaml
> fix: forward ref in button component

- apps/mochi-web/components/Header/MobileNav.tsx
- apps/mochi-web/components/MochiWidget/Recipient/RecipientItem.tsx
- apps/mochi-web/components/MochiWidget/Recipient/SelectedRecipient.tsx
- apps/mochi-web/components/Receipt/Template.tsx
- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/components/profile.tsx
- packages/ui/src/index.tsx
> refactor: migrate avatar component

- apps/mochi-web/components/profile-dropdrown.tsx
> refactor: use Dropdown consolelab/core instead

- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/MochiWidget/ChainPicker/ChainPicker.tsx
- apps/mochi-web/components/MochiWidget/MessagePicker/MessagePicker.tsx
- apps/mochi-web/components/MochiWidget/PlatformPicker/PlatformPicker.tsx
- apps/mochi-web/components/MochiWidget/Recipient/Recipient.tsx
- apps/mochi-web/components/MochiWidget/ThemePicker/ThemePicker.tsx
- apps/mochi-web/components/MochiWidget/Tip/StepOne.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenPicker.tsx
- apps/mochi-web/components/MochiWidget/WalletPicker/WalletPicker.tsx
> refactor: migrate Popover component to consolelab/core

- .changeset/tidy-planes-itch.md
- packages/components/icon-button/package.json
- packages/components/icon-button/src/icon-button.tsx
- pnpm-lock.yaml
> fix: apply polymorphic icon button

- packages/components/sidebar/src/sidebar-item.tsx
- packages/theme/src/components/sidebar.ts
Issue link: https://discord.com/channels/462663954813157376/1162221179025768499/1174375303687180298
> fix: sidebar in safari

- .changeset/quiet-chicken-complain.md
- packages/components/button/package.json
- packages/components/button/src/button.tsx
- pnpm-lock.yaml
> chore: apply polymorphic button

- .changeset/four-singers-watch.md
- packages/components/badge/package.json
- packages/components/dropdown/package.json
- packages/components/icon-button/package.json
- packages/components/input-field/package.json
- packages/components/input/__tests__/input.test.tsx
- packages/components/input/package.json
- packages/components/input/src/input.tsx
- packages/components/input/stories/input.stories.tsx
- packages/components/list/package.json
- packages/components/popover/package.json
- packages/components/select/package.json
- packages/components/sidebar/package.json
- packages/components/table/package.json
- packages/components/tabs/package.json
- packages/theme/src/components/input.ts
- pnpm-lock.yaml
> fix: update input component

- .changeset/tiny-panthers-move.md
- packages/theme/src/components/list.ts
> refactor: use semantic tailwind classes in list

- .changeset/wise-students-hug.md
- packages/theme/src/components/pagination.ts
> refactor: use semantic tailwind classes in pagination

- packages/theme/src/components/accordion.ts
- Migrate accordion semantic tailwind color
> refactor: migrate accordion semantic color

- packages/theme/src/components/badge.ts
Migrate badge component to use semantic variant
> refactor: migrate badge semantic colors

- .changeset/ninety-wombats-press.md
- packages/theme/src/components/section-list.ts
> refactor: use semantic tailwind classes in section list

- .changeset/rotten-eagles-drive.md
- packages/components/sidebar/__tests__/sidebar.test.tsx
- packages/theme/src/components/sidebar.ts
> refactor: use semantic tailwind classes in sidebar

- .changeset/wise-items-rule.md
- packages/theme/src/components/profile-badge.ts
> refactor: use semantic tailwind classes in profile badge

- .changeset/clean-dogs-accept.md
- packages/components/alert/__tests__/alert.test.tsx
- packages/components/alert/src/alert.tsx
- packages/components/alert/stories/alert.stories.tsx
- packages/theme/src/components/alert.ts
Migrate Alert component use semantic colors
> refactor: migrate alert component use semantic color

- .github/actions/discord-notify/action.yml
- .github/workflows/release.yml
> chore: update links for discord actions

- .changeset/tiny-ducks-remember.md
- packages/theme/src/components/input-field.ts
- Update input field tailwind semantic
> refactor: update input field semantic colors

- .changeset/calm-dolphins-cross.md
- Update missing changeset for accodion, badge
> chore: update changeset for accordion, badge

- .changeset/light-bats-attend.md
- packages/theme/src/components/table.ts
> refactor: use semantic tailwind classes in table

- .changeset/giant-hotels-drive.md
- packages/components/tabs/stories/tabs.stories.tsx
- packages/theme/src/components/tabs.ts
> refactor: use semantic tailwind classes in tabs

- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/components/MochiWidget/WalletPicker/WalletPicker.tsx
- apps/mochi-web/pages/_app.tsx
> fix: unsupported at() method

- .changeset/spicy-points-repeat.md
- packages/components/switch/__tests__/switch.test.tsx
- packages/components/switch/src/Switch.tsx
- packages/components/switch/stories/switch.stories.tsx
- packages/theme/src/components/switch.ts
> feat: update Switch component

- .github/workflows/discord-release-notify.yml
- .github/workflows/release.yml
> chore: update discord notify with multiple messages

- .changeset/late-needles-flow.md
- packages/theme/src/components/login-widget.ts
> refactor: use semantic tailwind classes in login widget

- .changeset/slow-dolls-admire.md
- packages/theme/src/components/popover.ts
> refactor: use semantic tailwind classes in popover

- .changeset/heavy-crabs-occur.md
- .changeset/lemon-seals-lie.md
- apps/mochi-web/components/profile-dropdrown.tsx
- packages/components/modal/src/modal.tsx
- packages/components/popover/src/popover.tsx
- packages/components/profile-badge/src/profile-badge.tsx
- packages/theme/src/components/modal.ts
- packages/theme/src/components/popover.ts
- packages/theme/src/components/select.ts
- Remove focus state on `select, modal, dropdown, popover` trigger element.
- Fix header bar profile badge
> fix: remove outline state trigger, fix header profile trigger

- .changeset/flat-laws-brush.md
- packages/theme/src/components/modal.ts
- Update modal use semantic color
> refactor: update modal use semantic color

- .changeset/good-emus-marry.md
- packages/components/select/stories/select.stories.tsx
- packages/theme/src/components/select.ts
Use semantic color for select component
> refactor: update select use semantic color

- .changeset/cold-seahorses-visit.md
- apps/mochi-web/pages/developer.tsx
- packages/components/tooltip/src/tooltip.tsx
- packages/components/tooltip/stories/tooltip.stories.tsx
- packages/theme/src/colors/common.ts
- packages/theme/src/components/tooltip.ts
- Update Tooltip use semantic color
> Refactor: update tooltip semantic color

- .changeset/good-penguins-scream.md
- .changeset/twelve-cows-double.md
- packages/components/icon-button/src/icon-button.tsx
- packages/components/icon-button/stories/icon-button.stories.tsx
- packages/theme/src/components/button.ts
- packages/theme/src/components/icon-button.ts
- Add variants for IconButton components
-  Use tailwind semantic for component
> feat: add icon button variants, use semantic color

- apps/mochi-web/components/app/Statistics.tsx
- apps/mochi-web/hooks/app/useFetchApplicationStats.ts
- apps/mochi-web/pages/app/index.tsx
- https://www.notion.so/console-labs/Listing-11a4fb55a3134ce291e72c526c72cfb0
> feat: get app stats api

- packages/storybook/src/colors.stories.mdx
- packages/theme/src/index.ts
> chore: add colors documentation

- packages/icons/scripts/build-clean-packages.ts
- packages/icons/scripts/clean.ts
- packages/icons/scripts/generate-icon-components.ts
- packages/icons/types.d.ts
- scripts/copy-files.ts
- scripts/modify-publish-root.ts
- scripts/script-utils.ts
> docs: update scripts docs

- .github/workflows/discord-release-notify.yml
- LICENSE
> fix: embeds size

- apps/mochi-web/components/MochiWidget/MessagePicker/MessagePicker.tsx
- apps/mochi-web/components/MochiWidget/ThemePicker/ThemePicker.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenPicker.tsx
> fix: rename input component

- apps/mochi-web/components/app/AppListing.tsx
- apps/mochi-web/components/app/NewAppForm.tsx
- apps/mochi-web/constants/api.ts
- apps/mochi-web/constants/routes.ts
- apps/mochi-web/hooks/app/useFetchApplicationList.ts
- apps/mochi-web/hooks/app/useFetchApplicationStats.ts
- apps/mochi-web/pages/app/index.tsx
> fix: app constants and handle errors

- apps/mochi-web/components/app/AppListing.tsx
- apps/mochi-web/components/app/Statistics.tsx
Resolve https://www.notion.so/console-labs/Listing-Text-styling-6e1e50eff48841dca2caba8fccc9a8a0
> fix(mochi-web): app listing text style

- packages/components/form/stories/form-control.stories.tsx
- Storybook incorrect TextField use
> fix: form-control story ui

- apps/mochi-web/components/AuthWidget/AuthPanel.tsx
- apps/mochi-web/components/BottomSheet/index.tsx
- apps/mochi-web/components/Feed/Row.tsx
- apps/mochi-web/components/Feed/index.tsx
- apps/mochi-web/components/MochiWidget/Recipient/SelectedRecipient.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/MonikerList.tsx
- apps/mochi-web/components/MochiWidget/WalletPicker/WalletList.tsx
- apps/mochi-web/next.config.js
> fix: tip widget

- .eslintignore
- package.json
- packages/core/src/index.ts
- plop/component/.eslintrc.js.hbs
- plop/component/README.md.hbs
- plop/component/__tests__/{{componentName}}.test.tsx.hbs
- plop/component/package.json.hbs
- plop/component/src/index.ts.hbs
- plop/component/src/{{componentName}}.tsx.hbs
- plop/component/stories/{{componentName}}.stories.tsx.hbs
- plop/component/tsconfig.json.hbs
- plop/component/tsup.config.ts.hbs
- plopfile.ts
- pnpm-lock.yaml
- From root project, run Plop to generate component by this command and following the instructions:
```
pnpm create:cmp
```
Output:
> chore: add plop for creating components

- packages/storybook/.storybook/main.ts
- packages/storybook/package.json
- packages/tsconfig/react-library.json
- pnpm-lock.yaml
> fix: build ds

- plop/component/__tests__/{{componentName}}.test.tsx.hbs
- plop/component/src/index.ts.hbs
- plop/component/src/{{componentName}}.tsx.hbs
- plop/component/stories/{{componentName}}.stories.tsx.hbs
> chore: update component template format

- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/package.json
- packages/storybook/package.json
- packages/theme/package.json
- pnpm-lock.yaml
> fix: fix build fail on local

- .changeset/bright-scissors-tap.md
- packages/components/button/stories/button.stories.tsx
- packages/theme/src/colors/semantic.ts
- packages/theme/src/components/button.ts
> feat(button): add white variant

- .changeset/green-dingos-smoke.md
- apps/mochi-web/components/app/detail/AppDetailIntegration.tsx
- apps/mochi-web/components/app/detail/AppDetailPageHeader.tsx
- apps/mochi-web/components/app/detail/CodeSnippet.tsx
- apps/mochi-web/constants/api.ts
- apps/mochi-web/pages/applications/[id].tsx
- apps/mochi-web/pages/applications/index.tsx
- packages/components/page-header/stories/page-header.stories.tsx
- packages/components/section-header/stories/section-header.stories.tsx
- packages/theme/src/components/alert.ts
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=74d4966670234848a941c7ca8e9ef5eb&pm=s
> feat: app detail secret key

- .changeset/ninety-avocados-press.md
- apps/mochi-web/components/app/Statistics.tsx
- apps/mochi-web/components/app/detail/AppDetailMembers.tsx
- apps/mochi-web/components/app/detail/AppDetailNewUrl.tsx
- apps/mochi-web/components/app/detail/AppDetailStatistics.tsx
- apps/mochi-web/components/app/detail/AppDetailUrl.tsx
- apps/mochi-web/constants/api.ts
- apps/mochi-web/hooks/app/useFetchApplicationDetailMembers.ts
- apps/mochi-web/pages/applications/[id].tsx
- packages/components/table/src/table.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=74d4966670234848a941c7ca8e9ef5eb&pm=s
> feat: app detail members

- .changeset/clever-ties-hammer.md
- apps/mochi-web/components/app/AppListing.tsx
- packages/components/table/src/table.tsx
- packages/theme/src/colors/common.ts
- packages/theme/src/colors/semantic.ts
- packages/theme/src/components/table.ts
> feat(table): support row click events

- .changeset/thin-humans-hang.md
- packages/components/table/package.json
- packages/components/table/src/table.tsx
- packages/components/table/stories/table.stories.tsx
- pnpm-lock.yaml
https://github.com/consolelabs/web-foundation/assets/12707960/a9c68618-bb9e-48ff-bf76-b1c95b424ce3
> feat(table): add sub component render

- .github/workflows/release.yml
- apps/mochi-web/components/app/detail/AppDetailApiCalls.tsx
- apps/mochi-web/types/mochi-pay-schema.ts
- package.json
- pnpm-lock.yaml
> chore: disable cache turbo release

- .github/workflows/release.yml
- packages/theme/tsconfig.json
> chore: add artifact upload logs

- .github/actions/setup-env/action.yml
- .github/workflows/release.yml
> chore: upgrade node v4

- .changeset/gold-elephants-exercise.md
> fix: package name

- .changeset/config.json
- .github/actions/setup-env/action.yml
> fix: node ci version

- .changeset/brown-bears-scream.md
- .changeset/chilled-hats-eat.md
- apps/mochi-web/components/MochiWidget/Recipient/SelectedRecipient.tsx
- packages/theme/src/components/avatar.ts
- packages/theme/src/components/profile-badge.ts
> fix: center avatar of selected recipient

- scripts/modify-publish-root.ts
> chore: remove package dist

- .changeset/chilled-rice-smell.md
- apps/mochi-web/components/auth-layout.tsx
- packages/theme/src/components/layout.ts
- packages/theme/src/components/page-content.ts
- packages/theme/src/components/page-header.ts
> fix: allow scrolling in page content only

- .github/CODEOWNERS
- .github/workflows/release.yml
> chore: add github trigger author check

- .changeset/chilled-pandas-breathe.md
- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/auth-layout.tsx
- apps/mochi-web/context/app/sidebar.tsx
- apps/mochi-web/pages/applications/index.tsx
- packages/components/layout/stories/layout.stories.tsx
- packages/components/page-header/__tests__/page-header.test.tsx
- packages/components/page-header/src/page-header.tsx
- packages/components/page-header/stories/page-header.stories.tsx
- packages/theme/src/components/page-header.ts
- packages/theme/src/components/top-bar.ts
> fix: header height and page header component

- .changeset/young-pianos-trade.md
- packages/components/alert/src/alert-action-group.tsx
- packages/components/alert/src/alert-body.tsx
- packages/components/alert/src/alert-cancel.tsx
- packages/components/alert/src/alert.tsx
- packages/components/alert/src/context.ts
- packages/components/alert/stories/alert.stories.tsx
- packages/theme/src/components/alert.ts
- Update Alert auto responsive layout
[screen-capture (12).webm](https://github.com/consolelabs/mochi-ui/assets/88917321/48691816-00d0-4e56-b31d-a43e25939000)
> fix: update alert auto responsive

- apps/mochi-web/pages/applications/[id].tsx
- apps/mochi-web/pages/applications/index.tsx
- apps/mochi-web/pages/index.tsx
- apps/mochi-web/pages/profile/index.tsx
update pages' title
- settings, server pages arenot implemented
> feat: update webpage title

- .changeset/good-forks-walk.md
- packages/components/pagination/src/pagination.tsx
- packages/theme/src/components/pagination.ts
Responsive pagination
[screen-capture (15).webm](https://github.com/consolelabs/mochi-ui/assets/88917321/72ee3911-3c4e-464f-ade1-4e9eed3f59d0)
> feat: update pagination responsive

- .changeset/funny-parrots-reflect.md
- packages/components/table/package.json
- packages/components/table/src/table.tsx
- packages/theme/src/components/table.ts
- pnpm-lock.yaml
use skeleton component for loading state table
> feat: use skeleton for table component

- scripts/release-notify.ts
> chore: update discord notify message footer

- apps/mochi-web/components/app/NewAppForm.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=c935657d548f4e6faa1e60e665c861f1&pm=s
> fix: new app form

- apps/mochi-web/components/Transaction/TransactionUsernameCell.tsx
- apps/mochi-web/components/Transaction/utils.ts
- apps/mochi-web/constants/api.ts
- apps/mochi-web/constants/transactions.ts
- apps/mochi-web/hooks/app/useFetchProfileTransaction.ts
- apps/mochi-web/pages/profile/transactions/index.tsx
- apps/mochi-web/types/mochi-pay-schema.ts
updated
[screen-capture (18).webm](https://github.com/consolelabs/mochi-ui/assets/88917321/1fefd9ac-790c-4fe7-8089-3b050c004801)
> feat: update profile transaction table

- apps/mochi-web/pages/profile/transactions/index.tsx
- update width for transaction table, datetime column
> fix: update width table for overflow

- .changeset/tender-singers-kneel.md
- apps/mochi-web/components/settings/notification/NotificationPage.tsx
- apps/mochi-web/hooks/settings/useFetchNotificationSettings.ts
- apps/mochi-web/pages/applications/[id].tsx
- packages/theme/src/components/section-header.ts
- pnpm-lock.yaml
- Notifcation settings page
TODO
- integrate real api
[screen-capture (20).webm](https://github.com/consolelabs/mochi-ui/assets/88917321/03d8a49f-2bba-4e68-b15f-8723dc94a9e1)
> feat: notification page UI

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/base/token-avatar/index.ts
- apps/mochi-web/components/base/token-avatar/token-avatar.tsx
> feat: token avatar component

- .changeset/pink-bears-marry.md
- apps/mochi-web/components/MochiWidget/index.tsx
- apps/mochi-web/components/Profile/PayLinkSection.tsx
- apps/mochi-web/components/Profile/PayMeSection.tsx
- apps/mochi-web/components/Profile/PaylinkSection.tsx
- apps/mochi-web/components/Profile/PaymeLinksTable.tsx
- apps/mochi-web/components/Profile/PaymeRequestsTable.tsx
- apps/mochi-web/components/Profile/PaymeSection.tsx
- apps/mochi-web/components/Profile/TableColumns.tsx
- apps/mochi-web/constants/api.ts
- apps/mochi-web/hooks/profile/useFetchPayRequests.ts
- apps/mochi-web/pages/profile/index.tsx
- apps/mochi-web/types/mochi-pay-schema.ts
- packages/components/table/src/table.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=da842467e78045acb40d66e682b3a356&pm=s
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=644a83a8d25f434d97eca47e944808e6&pm=s
> feat: overview payme and paylink

- apps/mochi-web/components/MochiWidget/index.tsx
> fix: mochi widget

- apps/mochi-web/components/Profile/PaylinkSection.tsx
- apps/mochi-web/components/Profile/PaymeLinksTable.tsx
- apps/mochi-web/components/Profile/PaymeRequestsTable.tsx
- apps/mochi-web/constants/api.ts
- apps/mochi-web/hooks/profile/useFetchPayRequests.ts
- apps/mochi-web/pages/profile/transactions/index.tsx
- apps/mochi-web/types/mochi-pay-schema.ts
- apps/mochi-web/utils/platform.ts
> fix: overview payme and paylink

- packages/components/button/src/button.tsx
- packages/storybook/.storybook/preview.ts
> fix: storybook source format

- .changeset/little-colts-give.md
- apps/mochi-web/components/DashboardLayout.tsx
- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/app/AppListing.tsx
- apps/mochi-web/components/app/detail/AppDetailPageHeader.tsx
- apps/mochi-web/components/profile-dropdrown.tsx
- apps/mochi-web/pages/applications/index.tsx
- packages/components/dropdown/src/dropdown.tsx
- packages/components/dropdown/stories/dropdown.stories.tsx
- Update dropdown api
- Migrate dropdown in mochi-web
> chore: migrate new dropdown api

- .changeset/nice-frogs-smell.md
- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/app/DeleteAppModal.tsx
- apps/mochi-web/components/app/detail/ResetKeyModal.tsx
- apps/mochi-web/pages/applications/index.tsx
- packages/components/modal/src/modal.tsx
- packages/components/modal/stories/modal.stories.tsx
- Update Modal Api
- Migrate to new Modal api
> refactor: migrate new modal api

- .changeset/brown-starfishes-dress.md
- apps/mochi-web/components/Header/Header.tsx
- packages/components/popover/src/popover.tsx
- packages/components/popover/stories/popover.stories.tsx
- Migrate using new Popover api
> chore: migrate new popover api

- apps/mochi-web/components/settings/general/DefaultMessage.tsx
- apps/mochi-web/components/settings/general/GeneralPage.tsx
- apps/mochi-web/components/settings/general/MessageModal.tsx
- apps/mochi-web/components/settings/general/TokenPriority.tsx
- apps/mochi-web/components/settings/general/types.ts
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=7bb63cd76a8849deba6f1df6c08d0be1&pm=s
> feat: settings default message

- .changeset/eighty-rocks-grow.md
- apps/mochi-web/components/settings/general/DefaultMessage.tsx
- apps/mochi-web/components/settings/general/GeneralPage.tsx
- apps/mochi-web/components/settings/general/MessageModal.tsx
- apps/mochi-web/components/settings/general/TransactionLimit.tsx
- apps/mochi-web/components/settings/general/TransactionLimitModal.tsx
- apps/mochi-web/components/settings/general/types.ts
- apps/mochi-web/constants/settings.ts
- packages/components/input/src/textfield.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=7bb63cd76a8849deba6f1df6c08d0be1&pm=s
> feat: settings transaction limit

- .github/workflows/deploy-mochi-web.yml
- .gitignore
- apps/mochi-web/package.json
- pnpm-lock.yaml
- To trigger a rebuild of this mochi-web and make it work when mochi.js updates to work with the mochi backend.
> chore: use latest mochijs

- .changeset/smooth-readers-train.md
- apps/mochi-web/components/Feed/Row.tsx
- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/PayRequest/UpperBody.tsx
- apps/mochi-web/components/Profile/PaymeRequestsTable.tsx
- apps/mochi-web/components/Receipt/Template.tsx
- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/components/Transaction/TransactionUsernameCell.tsx
- apps/mochi-web/components/profile.tsx
- packages/components/avatar/__tests__/avatar.test.tsx
- packages/components/avatar/package.json
- packages/components/avatar/src/avatar.tsx
- packages/components/avatar/src/util.ts
- packages/components/avatar/stories/avatar.stories.tsx
- packages/components/input/stories/input.stories.tsx
- packages/components/profile-badge/__tests__/profile-badge.test.tsx
- packages/components/profile-badge/src/profile-badge.tsx
- packages/theme/src/components/avatar.ts
- pnpm-lock.yaml
> feat: update avatar api

- .changeset/smooth-readers-train.md
- apps/mochi-web/components/Feed/Row.tsx
- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/PayRequest/UpperBody.tsx
- apps/mochi-web/components/Profile/PaymeRequestsTable.tsx
- apps/mochi-web/components/Receipt/Template.tsx
- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/components/Transaction/TransactionUsernameCell.tsx
- apps/mochi-web/components/profile.tsx
- packages/components/avatar/__tests__/avatar.test.tsx
- packages/components/avatar/package.json
- packages/components/avatar/src/avatar.tsx
- packages/components/avatar/stories/avatar.stories.tsx
- packages/components/input/stories/input.stories.tsx
- packages/components/profile-badge/__tests__/profile-badge.test.tsx
- packages/components/profile-badge/src/profile-badge.tsx
- packages/theme/src/components/avatar.ts
- pnpm-lock.yaml
This reverts commit 3641b29e53be170ac064429dcf2774e2a6143b8e.
things.
**Media …
> Revert "feat: update avatar api (#464)"

- apps/mochi-web/components/profile-dropdrown.tsx
- apps/mochi-web/components/settings/notification/NotificationPage.tsx
- apps/mochi-web/components/settings/notification/type.ts
- apps/mochi-web/constants/api.ts
- apps/mochi-web/hooks/settings/useFetchNotificationSettings.ts
- apps/mochi-web/types/mochi-pay-schema.ts
- apps/mochi-web/types/mochi-profile-schema.ts
- apps/mochi-web/types/mochi-schema.ts
- add api for notification page
- update uI
> fix: update ui, api for notification page

- .changeset/tough-bananas-lick.md
- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/PayRequest/Header.tsx
- apps/mochi-web/components/PayRequest/PayLink.tsx
- apps/mochi-web/components/PayRequest/PayMe.tsx
- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/pages/pay/[pay_code].tsx
- apps/mochi-web/pages/tx/[id].tsx
- packages/components/avatar/src/avatar.tsx
> fix: receipt and pay page

- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/constants/events.ts
> feat: tip widget listen for event focus amount input

- .changeset/old-hotels-live.md
- apps/mochi-web/components/settings/notification/NotificationPage.tsx
- packages/components/section-header/__tests__/section-header.test.tsx
- packages/components/section-header/package.json
- packages/components/section-header/src/context.ts
- packages/components/section-header/src/section-header.tsx
- packages/components/section-header/src/type.ts
- packages/components/section-header/stories/section-header.stories.tsx
- packages/theme/src/components/section-header.ts
- pnpm-lock.yaml
> feat: make section header composable

- .changeset/fluffy-ties-bow.md
- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenPicker.tsx
- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/base/token-avatar/token-avatar.tsx
- apps/mochi-web/components/base/token-table-list/index.tsx
- apps/mochi-web/components/base/token-table-list/token-table-list.tsx
- packages/components/table/src/table.tsx
> feat: token table list component

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/landing/TabbedFeatures.tsx
- apps/mochi-web/hooks/profile/useFetchProfileGlobalInfo.ts
- packages/theme/src/components/dropdown.ts
> fix: profile widget ui

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/pages/profile/index.tsx
> fix: profile widget buttons and tabs

- .changeset/unlucky-papayas-brake.md
- packages/theme/src/components/pagination.ts
> fix(pagination): wrong buttons alignment

- packages/components/table/src/table.tsx
- packages/components/table/stories/table.stories.tsx
- packages/theme/src/components/table.ts
https://github.com/consolelabs/mochi-ui/assets/44285614/5b49e187-9ef4-470b-aaf8-28bea783e35e
> fix: table style

- apps/mochi-web/components/SaveBar.tsx
- apps/mochi-web/components/settings/notification/NotificationPage.tsx
- loading state for notification
> fix: add loading state for notification page

- .changeset/serious-cameras-dress.md
- packages/components/pagination/src/pagination.tsx
- packages/components/pagination/src/utils.ts
- packages/components/pagination/stories/pagination.stories.tsx
- packages/theme/src/components/pagination.ts
> fix: pagination issues

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/TokenTableList.tsx
- apps/mochi-web/components/settings/general/GeneralPage.tsx
- apps/mochi-web/components/settings/notification/NotificationPage.tsx
- apps/mochi-web/pages/applications/[id].tsx
- packages/components/table/src/table.tsx
- packages/theme/src/components/table.ts
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=fea30ec73df0449fb78895890deae997&pm=s&pvs=31
> refactor: use save bar component

- .changeset/fifty-olives-arrive.md
- apps/mochi-web/components/DashboardLayout.tsx
- apps/mochi-web/components/PayRequest/LowerBody.tsx
- apps/mochi-web/components/Profile/PaylinkSection.tsx
- apps/mochi-web/components/Profile/PaymeSection.tsx
- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/components/Transaction/index.tsx
- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
- apps/mochi-web/components/app/detail/AppDetailApiCalls.tsx
- packages/components/badge/__tests__/badge.test.tsx
- packages/components/badge/src/badge.tsx
- packages/components/badge/src/context.ts
- packages/components/badge/src/index.ts
- packages/components/badge/src/type.ts
- packages/components/badge/stories/badge.stories.tsx
- packages/components/layout/stories/layout.stories.tsx
- packages/components/sidebar/__tests__/sidebar.test.tsx
- packages/components/sidebar/stories/sidebar.stories.tsx
- packages/components/table/__tests__/table.test.tsx
- packages/components/table/stories/table.stories.tsx
> feat: make badge composable

- .changeset/fluffy-monkeys-compete.md
- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/TokenTableList.tsx
- packages/theme/src/components/page-content.ts
> fix: profile widget

- apps/mochi-web/components/settings/notification/NotificationPage.tsx
- packages/components/section-header/src/context.ts
- packages/components/section-header/src/section-header.tsx
- packages/theme/src/components/section-header.ts
> fix: section-header remove redundant padding if dont have desc

- .changeset/eighty-rocks-grin.md
- .changeset/old-moose-share.md
- apps/mochi-web/components/settings/general/MessageModal.tsx
- apps/mochi-web/components/settings/general/MoneySource.tsx
- apps/mochi-web/components/settings/general/PrivacySetting.tsx
- apps/mochi-web/components/settings/general/ReceiverPlatform.tsx
- apps/mochi-web/components/settings/general/TransactionLimitModal.tsx
- apps/mochi-web/pages/profile/transactions/index.tsx
- packages/components/input/__tests__/input.test.tsx
- packages/components/input/src/textfield.tsx
- packages/components/select/package.json
- packages/components/select/src/context.ts
- packages/components/select/src/select.tsx
- packages/components/select/src/type.ts
- packages/components/select/stories/select.stories.tsx
- packages/icons/src/svg/line/spinner.svg
- packages/theme/src/components/select.ts
- packages/theme/src/components/textfield.ts
- pnpm-lock.yaml
> feat: update select component style

- .changeset/kind-ants-appear.md
- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/styles/global.css
- packages/components/pagination/__tests__/pagination.test.tsx
- packages/components/pagination/package.json
- packages/components/pagination/src/pagination.tsx
- packages/theme/src/components/pagination.ts
- packages/theme/src/components/select.ts
- pnpm-lock.yaml
> fix: use select component in pagination

- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
- apps/mochi-web/components/TransactionTable/types.ts
- apps/mochi-web/components/explore/index/sections/SummarySection.tsx
- apps/mochi-web/components/explore/index/sections/TransactionSection.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todolists/6813576240
> feat: explore page follow-up p2

- .changeset/small-cooks-drop.md
- packages/components/select/src/select.tsx
> fix: check if select is filled

- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
- use mochi-ui ScrollArea for TransactionTable
> refactor: use mochi-core scrollArea for transaction table

- .changeset/yellow-dingos-scream.md
- packages/components/avatar-group/stories/avatar-group.stories.tsx
- packages/components/avatar/__tests__/avatar.test.tsx
- packages/components/avatar/package.json
- packages/components/avatar/src/avatar.tsx
- packages/components/profile-badge/__tests__/profile-badge.test.tsx
- packages/theme/src/components/avatar.ts
- packages/theme/src/plugin.ts
- pnpm-lock.yaml
> feat: lazy load avatar using radix avatar

- apps/mochi-web/components/landing/GridFeatures.tsx
- apps/mochi-web/components/landing/TabbedFeatures.tsx
- apps/mochi-web/components/stats.tsx
- apps/mochi-web/pages/index.tsx
https://github.com/consolelabs/mochi-ui/assets/69586735/35f4e178-8df7-4174-80b0-88ae54583a00
> fix: sections alignment on landing page

- apps/mochi-web/components/SaveBar.tsx
- apps/mochi-web/components/settings/general/DefaultMessage.tsx
- apps/mochi-web/components/settings/general/GeneralPage.tsx
- apps/mochi-web/components/settings/general/PrivacySetting.tsx
- apps/mochi-web/components/settings/general/SocialAccountsPrivacy.tsx
- apps/mochi-web/components/settings/general/TokenPriority.tsx
- apps/mochi-web/components/settings/general/TransactionLimit.tsx
- apps/mochi-web/components/settings/general/TransactionPrivacy.tsx
- apps/mochi-web/components/settings/general/WalletsPrivacy.tsx
- apps/mochi-web/components/settings/notification/NotificationPage.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=3baf51aec0e043399cbd6140f1e061ca&pm=s
> fix: setting page

- apps/mochi-web/app/layout/index.tsx
- apps/mochi-web/pages/privacy.tsx
> fix: allow scrolling page content only

- apps/mochi-web/components/Feed/index.tsx
- apps/mochi-web/components/MochiWidget/Recipient/Recipient.tsx
- apps/mochi-web/components/TokenTableList.tsx
- Migrate to use ScrollArea mochi-core
> refactor: migrate mochi-ui scrollarea

- apps/mochi-web/app/layout/index.tsx
- apps/mochi-web/components/BottomSheet/index.tsx
- apps/mochi-web/components/Home/ApiIntegration.tsx
- apps/mochi-web/components/MochiWidget/index.tsx
- apps/mochi-web/pages/privacy.tsx
> fix: use dvh unit

- .changeset/itchy-cherries-unite.md
- apps/mochi-web/components/Transaction/index.tsx
- packages/components/pagination/src/pagination.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=59e9f06d55e04228bddb3c17fb8f05b5&pm=s
> fix: transaction page pagination

- .changeset/fluffy-dancers-compete.md
- packages/components/table/src/table.tsx
> feat(table): allow custom row className

- packages/components/avatar/package.json
- packages/components/avatar/src/avatar.tsx
- pnpm-lock.yaml
> fix: avatar window undefined

- apps/mochi-web/components/base/dnd/DndItem.tsx
- apps/mochi-web/components/settings/general/DefaultMessage.tsx
- apps/mochi-web/components/settings/general/TokenPriority.tsx
- apps/mochi-web/components/settings/general/TransactionLimit.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=2d0a916918854e4987a085df2fab8f35&pm=s
> refactor: setting edit and delete button

- apps/mochi-web/components/settings/general/DefaultMessage.tsx
- apps/mochi-web/components/settings/general/MessageModal.tsx
- apps/mochi-web/components/settings/general/PrivacySetting.tsx
- apps/mochi-web/components/settings/general/TransactionLimit.tsx
- apps/mochi-web/components/settings/general/TransactionLimitModal.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=3cf6956d349c4926baf142d1d728792d&pm=s&pvs=31
> fix: setting message and txn limit

- apps/mochi-web/package.json
- apps/mochi-web/tailwind.config.js
- packages/components/accordion/stories/accordion.stories.tsx
- packages/components/drawer/src/drawer.tsx
- packages/components/dropdown/src/dropdown.tsx
- packages/components/dropdown/src/type.ts
- packages/components/tooltip/src/tooltip.tsx
- packages/storybook/package.json
- packages/storybook/tailwind.config.js
- packages/theme/src/components/accordion.ts
- packages/theme/src/components/action-bar.ts
- packages/theme/src/components/drawer.ts
- packages/theme/src/components/dropdown.ts
- packages/theme/src/components/modal.ts
- packages/theme/src/components/popover.ts
- packages/theme/src/components/select.ts
- packages/theme/src/components/sidebar.ts
- packages/theme/src/components/tooltip.ts
- packages/theme/src/plugin.ts
- pnpm-lock.yaml
enter, leave animation for
- Modal
- Accordion
- Select
- Dropdown
- Drawer
- Tooltip
TODO
- update docs
> [WIP] fix: add animation for overlay components

- apps/mochi-web/.env.example
- apps/mochi-web/components/Feed/store.ts
- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
- apps/mochi-web/components/TransactionTable/types.ts
- apps/mochi-web/components/explore/index/stores/useTransactionStore.ts
- apps/mochi-web/envs.ts
- apps/mochi-web/tailwind.config.js
```
NEXT_PUBLIC_MOCHI_PAY_WSS="wss://api-preview.mochi-pay.console.so"
NEXT_PUBLIC_MOCHI_PAY_WSS="wss://api.mochi-pay.console.so"
```
> feat(mochi-web): explore page followup p4

- packages/storybook/src/installation.stories.mdx
- update installation document for animation
> feat: udpate documentation for installation

- packages/theme/src/components/toast.ts
- animation for toaster
[screen-capture (29).webm](https://github.com/consolelabs/mochi-ui/assets/88917321/4112daeb-1b57-4cdb-8b66-c3f6fdc4b684)
> feat: animation for toast

- apps/mochi-web/components/SaveBar.tsx
- apps/mochi-web/components/settings/general/GeneralPage.tsx
- apps/mochi-web/components/settings/general/MoneySource.tsx
- apps/mochi-web/components/settings/general/PrivacySetting.tsx
- apps/mochi-web/components/settings/general/TransactionLimitModal.tsx
- apps/mochi-web/constants/app.ts
- apps/mochi-web/constants/settings.ts
- apps/mochi-web/tailwind.config.js
- apps/mochi-web/types/app.ts
> fix: general settings

- apps/mochi-web/components/Amount.tsx
- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/components/TransactionTable/TransactionAction.tsx
- apps/mochi-web/components/TransactionTable/TransactionRecipients.tsx
- apps/mochi-web/components/TransactionTable/TransactionStatusIcon.tsx
- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
- apps/mochi-web/components/TransactionTable/TransactionTxGroup.tsx
- apps/mochi-web/components/TransactionTable/types.ts
- apps/mochi-web/components/TransactionTable/utils.tsx
- apps/mochi-web/components/explore/index/sections/TransactionSection.tsx
- apps/mochi-web/constants/routes.ts
- apps/mochi-web/constants/transactions.ts
- apps/mochi-web/pages/_document.tsx
- apps/mochi-web/tailwind.config.js
> feat: transaction table new ui

- apps/mochi-web/components/Feed/index.tsx
- apps/mochi-web/components/Profile/PaylinkSection.tsx
- apps/mochi-web/components/Profile/PaymeRequestsTable.tsx
- apps/mochi-web/components/Profile/TableColumns.tsx
- apps/mochi-web/components/app/detail/AppDetailApiCalls.tsx
- apps/mochi-web/components/app/detail/AppDetailPageHeader.tsx
- packages/components/button/package.json
- packages/components/button/src/button.tsx
- packages/theme/src/components/button.ts
- pnpm-lock.yaml
- use asChild prop for polymorphic - Button component
> feat: migrate to use asChild for Button component

- apps/mochi-web/components/settings/general/DefaultMessage.tsx
- apps/mochi-web/components/settings/general/GeneralPage.tsx
- apps/mochi-web/components/settings/general/MoneySource.tsx
- apps/mochi-web/components/settings/general/PrivacySetting.tsx
- apps/mochi-web/components/settings/general/TransactionLimit.tsx
- apps/mochi-web/components/settings/general/TransactionLimitModal.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6904521587
> fix: settings default value

- apps/mochi-web/components/Profile/TransactionSection.tsx
- Remove shadow on focus-visible transaction overview tab trigger
> fix: remove shadow outline on focus-visible

- apps/mochi-web/components/Header/Header.tsx
> fix: add hover state to navbar items

- apps/mochi-web/components/Profile/TransactionSection.tsx
- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
> fix: decrease trans table width and remove badge

- .changeset/short-glasses-explain.md
- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/Home/Banner.tsx
- apps/mochi-web/components/TransactionTable/TransactionRecipients.tsx
- apps/mochi-web/components/landing/GridFeatures.tsx
- apps/mochi-web/components/landing/SupportedPlatforms.tsx
- apps/mochi-web/components/landing/TabbedFeatures.tsx
- apps/mochi-web/components/stats.tsx
- apps/mochi-web/pages/changelog.tsx
- apps/mochi-web/pages/developer.tsx
- apps/mochi-web/pages/index.tsx
- apps/mochi-web/pages/profile/transactions/index.tsx
- apps/mochi-web/styles/global.css
- packages/components/layout/stories/layout.stories.tsx
- packages/components/page-content/__tests__/page-content.test.tsx
- packages/components/page-header/stories/page-header.stories.tsx
- packages/theme/src/components/footer.ts
- packages/theme/src/components/login-widget.ts
- packages/theme/src/components/page-content.ts
- packages/theme/src/plugin.ts
> feat: add container max width config

- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
> fix: remove container height of widget input

- packages/components/avatar/package.json
- pnpm-lock.yaml
> fix: peer dependency

- apps/mochi-web/components/TransactionTable/TransactionIssuedBy.tsx
- apps/mochi-web/components/TransactionTable/TransactionRecipients.tsx
- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
- apps/mochi-web/components/TransactionTable/utils.tsx
- apps/mochi-web/components/explore/index/components/ChainPicker.tsx
- apps/mochi-web/components/explore/index/sections/SummarySection.tsx
- apps/mochi-web/constants/transactions.ts
- apps/mochi-web/types/mochi-pay-schema.ts
> feat(mochi-web): explore page followup p5

- .changeset/chilled-llamas-watch.md
- packages/components/badge/package.json
- packages/components/badge/src/badge.tsx
- packages/components/badge/src/type.ts
- pnpm-lock.yaml
- Add Polymorphic to Badge component
- support forwardRef
> feat: support asChild for Badge, add forwardRef

- apps/mochi-web/components/MochiWidget/Recipient/ContactList.tsx
- Contact api fail on first page load
> fix: contact api fail on first load

- .changeset/chilled-llamas-watch.md
- .changeset/yellow-dolphins-kiss.md
- apps/mochi-web/components/MochiWidget/Recipient/SelectedRecipient.tsx
- apps/mochi-web/components/PayRequest/UpperBody.tsx
- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/Receipt/Template.tsx
- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/components/TransactionTable/TransactionIssuedBy.tsx
- apps/mochi-web/components/TransactionTable/TransactionRecipients.tsx
- apps/mochi-web/components/app/detail/AppDetailStatistics.tsx
- apps/mochi-web/components/profile.tsx
- packages/components/avatar-group/src/avatar-group.tsx
- packages/components/avatar-group/stories/avatar-group.stories.tsx
- packages/theme/src/components/avatar.ts
- packages/theme/src/components/profile-badge.ts
- Update Avatar, AvatarGroup size for consistency
> feat: update avatar, avatar group sizes

- apps/mochi-web/components/MochiWidget/Tip/store.tsx
- apps/mochi-web/components/Profile/TransactionSection.tsx
- apps/mochi-web/components/explore/index/sections/SummarySection.tsx
> fix: tweak

- apps/mochi-web/components/Profile/TransactionSection.tsx
- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6930053448
- https://3.basecamp.com/4108948/buckets/34574984/todos/6930050442
> fix: transaction section

- .changeset/silver-dogs-change.md
- apps/mochi-web/components/DashboardLayout.tsx
- apps/mochi-web/components/profile-dropdrown.tsx
- apps/mochi-web/constants/common.ts
- apps/mochi-web/package.json
- packages/components/sidebar/src/sidebar.tsx
- Display version from package json
> feat: add sidebar version prop, using version from packagejson in web

- apps/mochi-web/pages/changelog.tsx
- apps/mochi-web/styles/global.css
> feat: use typography and badge in changelog page

- apps/mochi-web/components/PayRequest/PayLink.tsx
- apps/mochi-web/components/PayRequest/PayMe.tsx
- apps/mochi-web/components/PayRequest/utils.ts
- apps/mochi-web/components/Receipt/index.tsx
- apps/mochi-web/components/TransactionPeekingCard/TransactionPeekingCard.tsx
- apps/mochi-web/components/TransactionPeekingCard/index.ts
- apps/mochi-web/components/TransactionTable/TransactionTable.tsx
- apps/mochi-web/pages/pay/[pay_code].tsx
- apps/mochi-web/styles/global.css
> feat(mochi-web): tx peeking card

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6944917217
https://github.com/consolelabs/mochi-ui/assets/44285614/a5a095be-821a-4b62-91a2-56067dd9a050
> refactor: profile widget tabs animation

- apps/mochi-web/tailwind.config.js
- packages/storybook/tailwind.config.js
> fix: include common colors in mochi web

- apps/mochi-web/pages/changelog.tsx
- apps/mochi-web/styles/global.css
- apps/mochi-web/types/mochi-schema.ts
> fix: update changelog styling

- packages/theme/src/components/button.ts
- Remove outlined button shadow
> feat: remove button variant outline shadow

- packages/storybook/.storybook/preview.ts
> fix: popover docs

- apps/mochi-web/components/settings/notification/NotificationPage.tsx
- apps/mochi-web/components/settings/notification/type.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/6958878766
> fix: settings notification

- apps/mochi-web/pages/changelog.tsx
- apps/mochi-web/types/mochi-schema.ts
- apps/mochi-web/utils/changelog.ts
> fix: changelog seo content

- apps/mochi-web/components/MochiWidget/ThemePicker/ThemePicker.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenPicker.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6958881144
> fix: tip widget tabs height

- packages/components/alert/src/alert-cancel.tsx
- Update cancel button color for alert component
> feat: update alert cancel btn color

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6969041185
> fix: remove profile widget init animation

- apps/mochi-web/tailwind.config.js
- packages/storybook/tailwind.config.js
- packages/theme/src/plugin.ts
> fix: make add common colors config true by default

- apps/mochi-web/store/wallets.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/6929449074
> fix: wallet chain icon

- apps/mochi-web/components/settings/general/MessageModal.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6959883147
> fix: settings default message

- apps/mochi-web/components/Profile/RecapSection.tsx
- apps/mochi-web/constants/api.ts
- apps/mochi-web/hooks/profile/useFetchMonthlyStats.ts
- apps/mochi-web/pages/profile/index.tsx
- apps/mochi-web/types/mochi-pay-schema.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/6959865673
> feat: overview recap

- apps/mochi-web/pages/changelog/[version].tsx
- apps/mochi-web/pages/changelog/index.tsx
- Remove regex validator for version query string
> fix: remove regex

- apps/mochi-web/components/Profile/ProfileWidget.tsx
> fix: profile widget total balance

- packages/storybook/.storybook/preview.tsx
- packages/storybook/package.json
- pnpm-lock.yaml
> chore: add dark theme to docs

- apps/mochi-web/components/Profile/RecapSection.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6986939094
- https://3.basecamp.com/4108948/buckets/34574984/todos/6986931158
- https://3.basecamp.com/4108948/buckets/34574984/todos/6986923628
> fix: recap section

- .changeset/sharp-bags-double.md
- packages/components/value-change/__tests__/value-change.test.tsx
- packages/theme/src/components/value-change.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/6969215612
> fix: value change icon color

- apps/mochi-web/components/app/Statistics.tsx
- apps/mochi-web/components/app/detail/AppDetailIntegration.tsx
- apps/mochi-web/components/app/detail/AppDetailMembers.tsx
- apps/mochi-web/components/app/detail/AppDetailNewUrl.tsx
- apps/mochi-web/components/app/detail/AppDetailPageHeader.tsx
- apps/mochi-web/components/app/detail/AppDetailStatistics.tsx
- apps/mochi-web/components/app/detail/AppDetailUrl.tsx
- apps/mochi-web/pages/applications/[id].tsx
- apps/mochi-web/types/mochi-pay-schema.ts
> feat(mochi-web): developer bugs and improvements (part 1)

- .changeset/odd-hats-lie.md
- packages/components/table/src/table.tsx
- packages/theme/src/components/table.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/6987320258
> fix: table header padding

- .changeset/famous-cameras-heal.md
- packages/theme/src/colors/semantic.ts
> fix: update divider color

- .changeset/chatty-feet-confess.md
- apps/mochi-web/app/layout/index.tsx
- apps/mochi-web/constants/api.ts
- apps/mochi-web/hooks/app/useFetchChangelogLatest.ts
- apps/mochi-web/pages/_app.tsx
- apps/mochi-web/pages/index.tsx
- apps/mochi-web/types/mochi-schema.ts
- packages/theme/src/plugin.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/6981334835
- https://3.basecamp.com/4108948/buckets/34574984/todos/7013968585
- https://3.basecamp.com/4108948/buckets/34574984/todos/7013970668
> feat: changelog alert

- apps/mochi-web/pages/changelog/[version].tsx
- Update UI for changelog detail
> feat: add back button

- apps/mochi-web/app/layout/footer.tsx
- apps/mochi-web/envs.ts
- Add substack email subscribe widget in change log pages
> feat: add substack email subscribe input

- apps/mochi-web/pages/_app.tsx
> fix: changelog alert link

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/TokenTableList.tsx
- apps/mochi-web/types/mochi-schema.ts
- packages/icons/src/svg/pictogram/arrow-down-down-colored.svg
- packages/icons/src/svg/pictogram/arrow-up-up-colored.svg
- https://3.basecamp.com/4108948/buckets/34574984/todos/6960185593
- https://3.basecamp.com/4108948/buckets/34574984/todos/7007125608
- https://3.basecamp.com/4108948/buckets/34574984/todos/7015421156
- https://3.basecamp.com/4108948/buckets/34574984/todos/7027903985
> feat: add binance to token table

- packages/theme/src/components/sidebar.ts
- Fix flicking outline sidebar item on focus change
> fix: flick outlinr on sidebar item transtition

- packages/icons/src/svg/line/arrow-right-short.svg
> fix: update stroke width icon arrow right

- apps/mochi-web/components/Header/Header.tsx
- apps/mochi-web/components/NotificationList/NotificationModal.tsx
- apps/mochi-web/components/NotificationList/Row.tsx
- apps/mochi-web/components/ProfileDropdown.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7028097691
- https://3.basecamp.com/4108948/buckets/34574984/todos/7028078665
> fix: show noti and tip icon on topbar mobile

- apps/mochi-web/components/DashboardLayout.tsx
- update icon color sidebar application detail page
> fix: update icon color sidebar application detail page

- .changeset/tricky-lies-wave.md
- apps/mochi-web/components/Amount.tsx
- apps/mochi-web/components/TransactionTable/types.ts
- apps/mochi-web/components/TransactionTable/utils.tsx
- packages/components/avatar-group/package.json
- packages/components/avatar-group/stories/avatar-group.stories.tsx
- packages/components/avatar/src/avatar.tsx
- pnpm-lock.yaml
- allow passing Svg component to smallSrc
> feat: update avatar component, support svg smallSrc

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/Profile/RecapSection.tsx
- apps/mochi-web/components/Profile/TransactionSection.tsx
- packages/theme/src/components/table.ts
- update background overview page
> fix: update background overview

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- packages/components/table/src/table.tsx
- packages/theme/src/components/table.ts
- fix table header sticky color
> fix: sticky table header background

- .changeset/gorgeous-panthers-hear.md
- apps/mochi-web/components/settings/general/AddNewWalletModal.tsx
- apps/mochi-web/components/settings/general/MoneySource.tsx
- packages/components/select/src/select.tsx
- packages/theme/src/components/select.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/7038933575
> feat: add new wallet

- apps/mochi-web/components/TokenAvatar.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7085036640
> fix: token avatar get emojis

- apps/mochi-web/components/app/Statistics.tsx
- apps/mochi-web/components/app/StatisticsBox.tsx
- apps/mochi-web/components/app/detail/AppDetailStatistics.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7095652548
> fix: app statistic box

- apps/mochi-web/components/NotificationList/index.tsx
- apps/mochi-web/components/NotificationList/util.ts
> fix: notification mark all as read

- apps/mochi-web/components/Profile/RecapSection.tsx
- apps/mochi-web/hooks/profile/useFetchMonthlyStats.ts
- apps/mochi-web/types/mochi-pay-schema.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/7099814568
> refactor: recap section

- apps/mochi-web/components/Profile/ProfileWidget.tsx
- apps/mochi-web/components/Profile/RecapSection.tsx
- background ProfileWidget and RecapSection
> fix: background color profile widget and recap

- apps/mochi-web/components/settings/general/MoneySource.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7125262165
https://github.com/consolelabs/mochi-ui/assets/44285614/6baefb5e-e07d-472a-8cef-ff30b1c15e5c
> fix: wallet list scroll

- apps/mochi-web/components/settings/general/AddNewWalletModal.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7119884324
- https://3.basecamp.com/4108948/buckets/34574984/todos/7125263261
> fix: connect wallet success handle

- apps/mochi-web/components/Profile/RecapSection.tsx
- apps/mochi-web/components/TokenTableList.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7119885598
- https://3.basecamp.com/4108948/buckets/34574984/todos/7119875841
> fix: recap exchange flow

- .changeset/dirty-berries-try.md
- apps/mochi-web/constants/api.ts
- apps/mochi-web/hooks/changelog/useFetchChangelogs.ts
- apps/mochi-web/pages/changelog/index.tsx
- packages/components/pagination/src/pagination.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6958885701
> feat: changelogs pagination

- .changeset/twelve-dolphins-add.md
- apps/mochi-web/components/Profile/TransactionSection.tsx
- apps/mochi-web/components/explore/index/sections/TransactionSection.tsx
- packages/components/pagination/package.json
- packages/components/pagination/src/pagination.tsx
- packages/components/pagination/stories/pagination.stories.tsx
- packages/theme/src/components/pagination.ts
- pnpm-lock.yaml
- https://3.basecamp.com/4108948/buckets/34574984/todos/6882678105
> feat: pagination custom page

- apps/mochi-web/components/ProfileDropdown.tsx
- apps/mochi-web/hooks/useTheme.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/7114804437
> fix: dark theme swtich behavior

- apps/mochi-web/components/settings/general/MoneySource.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7135115667
> fix: sort wallet list

- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/components/MochiWidget/TokenPicker/TokenItem.tsx
- apps/mochi-web/components/MonikerTableList.tsx
- apps/mochi-web/components/NotificationList/util.ts
- apps/mochi-web/components/Pay/Card.tsx
- apps/mochi-web/components/PayRequest/utils.ts
- apps/mochi-web/components/Receipt/utils.ts
- apps/mochi-web/components/TokenTableList.tsx
- apps/mochi-web/components/TransactionTable/utils.tsx
- apps/mochi-web/package.json
- apps/mochi-web/utils/string.ts
- pnpm-lock.yaml
> fix: formatTokenDigit

- apps/mochi-web/components/MochiWidget/AmountInput/AmountInput.tsx
- apps/mochi-web/components/MochiWidget/index.tsx
> fix: mochi widget scroll into view
