apps/mochi-web/components/auth-layout.tsx, packages/ui/src/sidebar/sidebar-item-list.tsx, packages/ui/src/sidebar/sidebar.tsx
=> fix: sidebar tooltip and expand the invi box

packages/theme/src/components/sidebar.ts, packages/ui/src/sidebar/sidebar-item.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=ad50a5dbd1e548798cbae698f896668c&pm=s
=> fix: active state icon color

.changeset/hungry-stingrays-behave.md, packages/theme/src/components/input-field.ts
Remove extra outline in input field:
=> fix(input-field): remove extra outline

.changeset/dirty-rings-deliver.md, packages/theme/src/components/input.ts
**NOTE: I cannot reproduce this in local storybook but online documents have shown that to use `outline-none` instead of `outline-0` so maybe that will fix it**
=> fix: input safari focus

.github/actions/discord-notify/action.yml, .github/workflows/release.yml
**Note**: Add `DISCORD_WEBHOOK` to Github Secret variables before merge
=> chore: add discord notify github action

.changeset/small-steaks-kneel.md, packages/theme/src/colors/semantic.ts, packages/theme/src/components/button.ts
Update styles for link variant:
=> fix(button): update style for link variant

apps/mochi-web/components/Pay/ShareButton.tsx, apps/mochi-web/components/app/DeleteAppModal.tsx, apps/mochi-web/components/app/NewAppForm.tsx, apps/mochi-web/components/app/detail/AppDetailStatistics.tsx, apps/mochi-web/pages/_app.tsx, apps/mochi-web/pages/applications/[id].tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=4e282e12206a42ada9a835e06bfe74a0&pm=s
=> refactor: replace alert with toast

.changeset/strange-kiwis-work.md, apps/mochi-web/components/app/detail/AppDetailPageHeader.tsx, apps/mochi-web/pages/applications/[id]/revenue.tsx, apps/mochi-web/pages/applications/index.tsx, apps/mochi-web/pages/profile/transactions/index.tsx, apps/mochi-web/pages/settings.tsx, packages/components/layout/stories/layout.stories.tsx, packages/components/page-header/__tests__/page-header.test.tsx, packages/components/page-header/package.json, packages/components/page-header/src/page-header.tsx, packages/components/page-header/src/type.ts, packages/components/page-header/stories/page-header.stories.tsx, packages/theme/src/components/page-header.ts, pnpm-lock.yaml
=> feat: make page header composable

apps/mochi-web/components/MochiWidget/PlatformPicker/type.ts, apps/mochi-web/components/TransactionTable/TransactionTable.tsx, apps/mochi-web/components/TransactionTable/utils.ts, apps/mochi-web/components/explore/index/components/ChainPicker.tsx, apps/mochi-web/components/explore/index/components/PlatformPicker.tsx, apps/mochi-web/components/explore/index/components/index.ts, apps/mochi-web/components/explore/index/sections/SummarySection.tsx, apps/mochi-web/components/explore/index/sections/TransactionSection.tsx, apps/mochi-web/components/explore/index/stores/useTransactionStore.ts, apps/mochi-web/components/explore/index/stores/useTransactionSummaryStore.ts, apps/mochi-web/constants/transactions.ts, apps/mochi-web/pages/explore.tsx
Please note that the API is incomplete. The params are there but will not be processed on the BE.
**Media**
=> feat: network and platform filters for explore transaction table

apps/mochi-web/components/TransactionTable/TransactionTable.tsx, packages/components/scroll-area/src/scroll-area.tsx
- show scrollbar on scroll only
=> fix: shrink scrollbar to table body only in tokenpicker

apps/mochi-web/components/TokenTableList.tsx
- shrink scrollbar to fit table body
=> fix: shrink scrollbar in token picker to fit table body

apps/mochi-web/components/TransactionTable/TransactionTable.tsx, apps/mochi-web/components/TransactionTable/utils.ts, apps/mochi-web/components/explore/index/sections/SummarySection.tsx, apps/mochi-web/components/explore/index/stores/useTransactionStore.ts, apps/mochi-web/constants/transactions.ts, apps/mochi-web/package.json, pnpm-lock.yaml
=> feat(mochi-web): explore page followup p3

apps/mochi-web/components/settings/general/DefaultMessage.tsx, apps/mochi-web/components/settings/general/MessageModal.tsx, apps/mochi-web/components/settings/general/TokenPriority.tsx, apps/mochi-web/components/settings/general/TransactionLimit.tsx, apps/mochi-web/components/settings/general/TransactionLimitModal.tsx
- https://www.notion.so/console-labs/e8a2f8df770942af8bc5df33760960c8?v=422febebdba24e178a8f593e333b1893&p=71c963c16e6543d698c220a9b1b3a08d&pm=s
https://github.com/consolelabs/mochi-ui/assets/44285614/8b0fb214-873a-48d2-8b1f-bbfe412237c7
=> fix: require at lease one record for default message limit transaction

.changeset/serious-cougars-care.md, packages/components/icon-button/package.json, packages/components/icon-button/src/icon-button.tsx, pnpm-lock.yaml
- Migrate to use `asChild` for IconButton component
=> feat: migrate iconbutton to use asChild prop

.changeset/silly-grapes-live.md, packages/components/action-bar/src/action-bar-action-group.tsx, packages/components/action-bar/src/action-bar-body.tsx, packages/components/action-bar/src/action-bar-cancel.tsx, packages/components/action-bar/src/action-bar-confirm.tsx, packages/components/action-bar/src/action-bar-content.tsx, packages/components/action-bar/src/action-bar-description.tsx, packages/components/action-bar/src/action-bar-title.tsx, packages/components/action-bar/src/action-bar-trigger.tsx, packages/components/alert/package.json, packages/components/alert/src/alert-action-group.tsx, packages/components/alert/src/alert-body.tsx, packages/components/alert/src/alert-cancel.tsx, packages/components/alert/src/alert-close.tsx, packages/components/alert/src/alert-confirm.tsx, packages/components/alert/src/alert-description.tsx, packages/components/alert/src/alert-icon.tsx, packages/components/alert/src/alert-link.tsx, packages/components/alert/src/alert-title.tsx, packages/components/alert/src/alert.tsx, packages/components/alert/stories/alert.stories.tsx, packages/components/toast/package.json, packages/components/toast/src/toast-body.tsx, packages/components/toast/src/toast-close.tsx, packages/components/toast/src/toast-description.tsx, packages/components/toast/src/toast-icon.tsx, packages/components/toast/src/toast-link.tsx, packages/components/toast/src/toast-title.tsx, packages/components/toast/src/toast.tsx, pnpm-lock.yaml
- Migrate Alert component to support `asChild`, remove `as` props
- Update Toast, ActionBar to use new Alert type api
=> feat: migrating alert component

apps/mochi-web/components/Profile/ProfileWidget.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6969182239
https://github.com/consolelabs/mochi-ui/assets/44285614/5354b645-7af8-41c2-90bb-e23c1efb336f
=> fix: profile widget init balance loading

apps/mochi-web/pages/changelog/[version].tsx, packages/theme/src/components/typography.ts
Fix share link title color, letter spacing
=> fix: update style sharelink title

apps/mochi-web/components/Profile/RecapSection.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7027893553
=> fix: recap section font

apps/mochi-web/components/NotificationList/index.tsx, apps/mochi-web/components/ProfileDropdown.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7027917230
=> fix: profile and notification dropdown

.changeset/ninety-phones-run.md, apps/mochi-web/components/app/detail/AppDetailApiCalls.tsx, packages/components/table/src/table.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/6929435955
- https://3.basecamp.com/4108948/buckets/34574984/todos/7001483248
=> fix: log table row click and empty state

apps/mochi-web/components/Profile/RecapSection.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7089814618
=> fix: recap vault name

.changeset/cuddly-bears-push.md, apps/mochi-web/components/Profile/ProfileWidget.tsx, apps/mochi-web/components/TokenTableList.tsx, packages/theme/src/components/table.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/7083002469
- https://3.basecamp.com/4108948/buckets/34574984/todos/7083020897
- https://3.basecamp.com/4108948/buckets/34574984/todos/7082983117
- https://3.basecamp.com/4108948/buckets/34574984/todos/7095679179
- https://3.basecamp.com/4108948/buckets/34574984/todos/7099897326
=> fix: balance table

.changeset/silver-dryers-bathe.md, apps/mochi-web/components/app/detail/AppDetailStatistics.tsx, apps/mochi-web/pages/applications/[id].tsx, packages/theme/src/components/content-editable.ts
- https://3.basecamp.com/4108948/buckets/34574984/todos/6929418708
=> fix: edit app name and desc

apps/mochi-web/components/Header/Header.tsx, apps/mochi-web/components/Profile/ProfileWidget.tsx, packages/web3/connect-wallet-widget/src/connect-wallet-widget.tsx
=> fix: header color, sort chain by total asset, add extension download link

apps/mochi-web/components/Changelog/ChangelogDetailTitle/ChangelogDetailTitle.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7114796032
=> fix: changelog title align center with button

apps/mochi-web/components/Amount.tsx, apps/mochi-web/components/MochiWidget/TransactionPreview/TransactionPreview.tsx
- https://3.basecamp.com/4108948/buckets/34574984/todos/7090682508
=> fix: mochi widget preview usd amount to token amount
